drop table if exists upload_audit;
drop table if exists managed_user;
drop table if exists app_admin;

create table if not exists app_admin (
    username varchar(50) primary key,
    password varchar(100) not null
);

create table if not exists managed_user (
    user_id bigint generated by default as identity primary key,
    name varchar(120) not null,
    email varchar(160) not null unique,
    role varchar(40) not null,
    status varchar(30) not null
);

create table if not exists upload_audit (
    upload_id bigint generated by default as identity primary key,
    file_name varchar(200) not null,
    row_count int not null,
    processing_status varchar(30) not null
);
